# Generated by Django 3.2 on 2022-11-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20221117_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origin_bag',
            new_name='original_bag',
        ),
    ]
